### ISSUE TITLE
!@#$@#$!#$!@something is in trouble please read this!@#$!@#$!@#$

### ISSUE THREAD

**Issue by lcy8047** [weaver9651/emacs_setting#1]
[https://github.com/autowarefoundation/autoware](https://github.com/autowarefoundation/autoware)
[https://github.com/ClemensElflein/OpenMower](https://github.com/ClemensElflein/OpenMower)
[https://github.com/cyberbotics/webots](https://github.com/cyberbotics/webots)
[https://github.com/chvmp/champ](https://github.com/chvmp/champ)
[https://github.com/ApolloAuto/apollo-platform](https://github.com/ApolloAuto/apollo-platform)
[https://github.com/OpenQuadruped/spot_mini_mini](https://github.com/OpenQuadruped/spot_mini_mini)
[https://github.com/robin-shaun/XTDrone](https://github.com/robin-shaun/XTDrone)
[https://github.com/Geonhee-LEE/mpc_ros](https://github.com/Geonhee-LEE/mpc_ros)
[https://github.com/uuvsimulator/uuv_simulator](https://github.com/uuvsimulator/uuv_simulator)
[https://github.com/KumarRobotics/kr_autonomous_flight](https://github.com/KumarRobotics/kr_autonomous_flight)

**Comment by weaver9651** [comment]
LGTM!
